from __future__ import annotations

import json
from pathlib import Path

from pydantic import TypeAdapter

from app.domain.models import Chunk, DocumentView


class ArtifactStore:
    """Loads reviewed, immutable artifacts generated by the offline ingestion path."""

    def __init__(self, corpus_path: Path | None = None) -> None:
        path = corpus_path or Path(__file__).parents[1] / "data" / "corpus.json"
        raw = json.loads(path.read_text(encoding="utf-8"))
        self.corpus_version: str = raw["corpus_version"]
        self.notice: str = raw["notice"]
        self.documents = TypeAdapter(list[DocumentView]).validate_python(raw["documents"])
        self.chunks = TypeAdapter(list[Chunk]).validate_python(raw["chunks"])
        self._documents_by_id = {item.id: item for item in self.documents}

    @property
    def public_documents(self) -> list[DocumentView]:
        """Return the reviewer-facing corpus: three narrative PDFs and three QRTs.

        Older web-page and synthetic fixtures stay loaded for regression tests, but
        they are deliberately excluded from the deployed document library.
        """
        public_types = {"Official narrative PDF", "Official public QRT PDF"}
        return [doc for doc in self.documents if doc.document_type in public_types]

    def selected_chunks(self, document_ids: list[str]) -> list[Chunk]:
        selected = set(document_ids)
        if not selected:
            selected = {doc.id for doc in self.public_documents}
        return [chunk for chunk in self.chunks if chunk.document_id in selected]

    def validate_document_ids(self, document_ids: list[str]) -> list[str]:
        valid = set(self._documents_by_id)
        unknown = sorted(set(document_ids) - valid)
        if unknown:
            raise ValueError(f"Documents inconnus dans le périmètre : {', '.join(unknown)}")
        return list(dict.fromkeys(document_ids))


store = ArtifactStore()
