from __future__ import annotations

import json
from pathlib import Path

from pydantic import TypeAdapter

from app.domain.models import Chunk, DocumentView


class ArtifactStore:
    """Loads reviewed, immutable artifacts generated by the offline ingestion path."""

    def __init__(self, corpus_path: Path | None = None) -> None:
        path = corpus_path or Path(__file__).parents[1] / "data" / "corpus.json"
        raw = json.loads(path.read_text(encoding="utf-8"))
        self.corpus_version: str = raw["corpus_version"]
        self.notice: str = raw["notice"]
        self.documents = TypeAdapter(list[DocumentView]).validate_python(raw["documents"])
        self.chunks = TypeAdapter(list[Chunk]).validate_python(raw["chunks"])
        self._documents_by_id = {item.id: item for item in self.documents}

    def selected_chunks(self, document_ids: list[str]) -> list[Chunk]:
        selected = set(document_ids)
        if not selected:
            selected = {doc.id for doc in self.documents if doc.status != "synthetic"}
        return [chunk for chunk in self.chunks if chunk.document_id in selected]

    def valid_document_ids(self, document_ids: list[str]) -> list[str]:
        valid = set(self._documents_by_id)
        return [document_id for document_id in document_ids if document_id in valid]


store = ArtifactStore()

